# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: ["master"]

jobs:
  make-semver:
    name: Build SemVersion from Git history
    runs-on: ubuntu-latest
    timeout-minutes: 2
    outputs:
      version_name: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

  build-flutter:
    name: flutter test
    runs-on: ubuntu-latest
    timeout-minutes: 35
    needs: make-semver
    permissions:
      contents: write
    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: "temurin"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
      - run: flutter --version
      # leave commented for now till env file setup is complete
      - name: Create ENV file from secrets
        run: echo "${{ secrets.BRANDS_LABELS_ENV_STAGE }}" > env

        # Setup Ruby, Bundler, and Gemfile dependencies
      - name: Setup Fastlane
        uses: ruby/setup-ruby@c7079efafd956afb5d823e8999c2506e1053aefa
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - name: Checkout meta_package
        uses: actions/checkout@v3
        with:
          repository: MioModaFlutter/Meta-Package
          token: ${{ secrets.GH_TOKEN }}
          path: Meta-Package

      - name: Increment build number
        run: bundle exec fastlane incr_build
        working-directory: android

      - name: Fetch dependencies (flutter pub get)
        run: flutter pub get
        timeout-minutes: 5

      - name: Build APK
        run: flutter build apk --flavor prod -t lib/app/main/main.prod.dart --build-name=${{needs.make-semver.outputs.version_name}}
        timeout-minutes: 20

      - name: Build appbundle
        run: flutter build appbundle --flavor prod -t lib/app/main/main.prod.dart --build-name=${{needs.make-semver.outputs.version_name}}
        timeout-minutes: 5

      - name: Deploy to google play store production track
        run: bundle exec fastlane deploy
        working-directory: android

      - name: upload artifact to Firebase App Distribution android
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/flutter-apk/app-prod-release.apk
  build-ios:
    name: iOS build
    needs: make-semver
    runs-on: macos-latest
    env:
      VERSION_NAME: ${{needs.make-semver.outputs.version_name}}
      MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_REPO_PASSWORD }}
      FASTLANE_USER: sololuxurydubai1@gmail.com
      FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_ID_PASSWORD }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

    timeout-minutes: 60
    permissions:
      contents: write

    steps:
      - name: work around permission issue
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Create ENV file from secrets
        run: echo "${{ secrets.BRANDS_LABELS_ENV_STAGE }}" > env

      - name: Create SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout meta_package
        uses: actions/checkout@v3
        with:
          repository: MioModaFlutter/Meta-Package
          token: ${{ secrets.GH_TOKEN }} # `GH_PAT` is a secret that contains your PAT
          path: Meta-Package
      - name: Fetch dependencies (flutter clean)
        run: flutter clean
      - name: Fetch dependencies (flutter pub get)
        run: flutter pub get
        timeout-minutes: 5
      - run: bundle install
        working-directory: ios
      - run: rm Podfile.lock
        working-directory: ios
      - run: pod repo update
        working-directory: ios
      - run: pod install
        working-directory: ios
      - run: echo $CERTIFICATE_BASE64 | base64 --decode > AuthKey_3D5768A3JM.p8
        working-directory: ios
        env:
          CERTIFICATE_BASE64: ${{ secrets.APP_STORE_API_KEY }}

      - run: flutter build ios -t lib/app/main/main.prod.dart --release --no-codesign --no-sound-null-safety --flavor=prod --build-name=${{needs.make-semver.outputs.version_name}}
      - run: bundle exec fastlane release
        working-directory: ios
        env:
          VERSION_NAME: ${{needs.make-semver.outputs.version_name}}
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_REPO_PASSWORD }}
          FASTLANE_USER: sololuxurydubai1@gmail.com
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_APPLE_ID_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}

      - run: cat /Users/runner/Library/Logs/gym/Runner-prod.log
        if: success()||failure()
